name: CI
on: pull_request

jobs:
  release:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"
          cache: true

      - name: test
        run: go test -v ./...
